### ISSUE TITLE
i tried to convert dcm file to dcm-rt using this script.   but  raise ValueError("Input file is not of modality 'RTDOSE'.(Returning False.)")

### ISSUE THREAD

**Issue by topdeveloper424** [chris201706/PyEQD2#1]

**Comment by chris201706** [comment]
Not sure what you tried to accomplish. The purpose of PyEQD2 is to convert dose values in an existing **DICOM-RT** file to EQD2. Other DICOM files, such as images, will not work, that's why the modality of the input file is checked first (and in your case, why an error was raised).

**Comment by topdeveloper424** [comment]
Thank you
