### ISSUE TITLE
viewing the EQD2 dose in commercial planning systems

### ISSUE THREAD

**Issue by gleesoi** [chris201706/PyEQD2#2]
I am encountering an issue when trying to load and view the new ray station EQD2 dose in prosoma ("error cant read data") . i have managed to load ok into ray station but the dose is scaling much higher than expected. do i need to change something specifically to correctly normalize for raystation? thanks

**Comment by chris201706** [comment]
Interesting. Here's my answer:
1) I only had access to RayStation 6 when coding the tool, so unfortunately, I wasn't able to test it on other planning systems. 
2) It may have something to do with which dose distribution you're using (total dose or single fraction). Also, which values did you use for the alpha/beta ratio and the number of fractions?

Just made some changes to the README that provide some clarity regarding tested systems and dose distribution input.

**Comment by gleesoi** [comment]
thanks Chris I subsequently ran it on another two different patients and it worked fine loading into raystation 10A and compared very well against another EQD2 script I ran. I'm not not entirely sure what happened the first time with dose scaling. cheers

**Comment by chris201706** [comment]
I'm glad to hear it all worked out!
